language: node_js
#  latest stable Node.js release
node_js: lts/*
addons:
  chrome: stable # make Chrome available
# Cache node packages between jobs
cache: npm
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # enable building pull requests.
    - master
    - production

script:
  - npm run lint
  # - npm run test
  - npm run generate:modern

before_deploy:
  - npx semantic-release

deploy:
  - provider: surge
    domain: daim.dev
    project: ./dist
    edge: true # opt in to dpl v2
    on:
      branch: master

  - provider: surge
    domain: staging.daim.dev
    project: ./dist
    edge: true # opt in to dpl v2
    on:
      all_branches: true

after_success:
  # - npm run lh -- $APP_URL
  - npm run lhci:autorun
