language: node_js
#  latest stable Node.js release
node_js: lts/*
addons:
  chrome: stable # make Chrome available
# Cache node packages between jobs
cache: npm

script:
  - npm run lint
  # - npm run test
  - npm run build:export
  - npx semantic-release

deploy:
  - provider: surge
    domain: daim.dev
    project: ./dist
    # edge: true # opt in to dpl v2
    skip_cleanup: true
    on:
      branch: master

  - provider: surge
    domain: staging.daim.dev
    project: ./dist
    # edge: true # opt in to dpl v2
    skip_cleanup: true
    on:
      all_branches: true

  - provider: firebase
    skip_cleanup: true
    project: default
    token:
      secure: Ou/hhyRUnxcZGkV7Cei+XASsIDEPMOmIwvoje2lmqT7T7sp0YQgM1ztev6kIoJmIgt0oBernVCudDwsb4LXsYafa0J6K7bQkm5SDfiHs86EhLWCMB2HFhIzr2Vp+TYzdm0NH2oojYMLBAdVizpOZIuNaOekauZBxJ1VIVt+5jc9sXHdjEnAsqvR9NgxvjsSa+hI/XcesA51jYP9ID8GaRcE5gNfBeiRmqLSUH0H3ot2tC8k8Z1Cw9zAN43al3yWpJB1VjVlwyj7g4hfW2k2vnUT8Q9aIFGBq+I5JYsH4hdg835y0J6ES5seGOQ2PKrNXhMq9WTr4jaLOPZ4FDX+GNon8DdlDXjDyRhlu/f69rlCp2weLskVKjfqiOOATi0Ax2XAU9+KyivOxqTIiGuB/5j0SF3F2iBn0KcpambDz4nf89NBA7SJbUNSAINlK35TAXJYtcfoK/gEKAfRaaZMTEz+2iEh0Ozkvw5sTEZgIubzpT5gVQLuf9oit46rqhv7cadF1uwSwxKa/eCuKmxxXA+Ti6PiTq0yvzniLEIcrDzVgyKA2kSz2t2pzYQWUsyBrNRS4dFQdt6RjAiAvY+vjJo+rfreFm29uGhTM0SfeWgYmo90VxzsfVDOIAgJSypW3L5AGZBO9N+yK/q4nO5+5rlfzBamrWaAo/maG+CcbqRY=
    on:
      branch: master

after_success:
  - npm run lhci:autorun
